#!/bin/bash
# Setup Documentation Pre-Commit Hook
#
# Installs a git pre-commit hook that automatically maintains documentation
# before each commit.
#
# Usage: bash scripts/setup-docs-precommit.sh [--uninstall]

set -e

HOOK_FILE=".git/hooks/pre-commit"
BACKUP_FILE=".git/hooks/pre-commit.backup"

# Check if --uninstall flag is provided
if [ "$1" = "--uninstall" ]; then
    echo "🗑️  Uninstalling documentation pre-commit hook..."

    if [ -f "$BACKUP_FILE" ]; then
        mv "$BACKUP_FILE" "$HOOK_FILE"
        echo "✅ Restored original pre-commit hook"
    elif [ -f "$HOOK_FILE" ]; then
        rm "$HOOK_FILE"
        echo "✅ Removed documentation pre-commit hook"
    else
        echo "ℹ️  No pre-commit hook found"
    fi

    exit 0
fi

echo "========================================"
echo "📋 Setup Documentation Pre-Commit Hook"
echo "========================================"
echo ""

# Check if git repo
if [ ! -d ".git" ]; then
    echo "❌ Error: Not a git repository"
    exit 1
fi

# Backup existing hook if present
if [ -f "$HOOK_FILE" ]; then
    echo "⚠️  Existing pre-commit hook found"
    echo "   Creating backup: $BACKUP_FILE"
    cp "$HOOK_FILE" "$BACKUP_FILE"
    echo ""
fi

# Create pre-commit hook
cat > "$HOOK_FILE" << 'EOF'
#!/bin/bash
# Documentation Pre-Commit Hook
# Auto-generated by scripts/setup-docs-precommit.sh
# DO NOT EDIT - Changes will be overwritten

set -e

echo ""
echo "📚 Running documentation maintenance..."
echo ""

# Check if documentation-related files changed
DOCS_CHANGED=$(git diff --cached --name-only | grep -E '(^docs/|^app/server/routers/|^lib/db/schema\.ts|^components/|\.env\.example)' || true)

if [ -z "$DOCS_CHANGED" ]; then
    echo "ℹ️  No documentation-related files changed, skipping"
    exit 0
fi

echo "📊 Changed files requiring documentation update:"
echo "$DOCS_CHANGED" | sed 's/^/   - /'
echo ""

# Step 1: Derive repo facts
echo "🔍 Step 1/5: Deriving repository facts..."
pnpm docs:facts || {
    echo "❌ Failed to derive repo facts"
    exit 1
}

# Step 2: Extract documentation tags
echo "📝 Step 2/5: Extracting documentation tags..."
pnpm docs:extract || {
    echo "⚠️  Warning: Documentation extraction had issues (non-critical)"
}

# Step 3: Build unified documentation
echo "🔨 Step 3/5: Building unified documentation..."
pnpm docs:build || {
    echo "⚠️  Warning: Documentation build had issues (non-critical)"
}

# Step 4: Generate indices
echo "📇 Step 4/5: Generating documentation indices..."
pnpm docs:generate:doc-index || {
    echo "⚠️  Warning: Doc index generation had issues (non-critical)"
}

# Step 5: Validate documentation
echo "✅ Step 5/5: Validating documentation..."
pnpm docs:validate || {
    echo ""
    echo "❌ Documentation validation failed!"
    echo ""
    echo "Common fixes:"
    echo "  - Add missing frontmatter (title, description, audience, status)"
    echo "  - Fix broken links"
    echo "  - Review drift reports"
    echo ""
    echo "To skip validation (NOT RECOMMENDED):"
    echo "  git commit --no-verify"
    echo ""
    exit 1
}

# Auto-stage generated files
echo ""
echo "📦 Auto-staging generated documentation files..."

GENERATED_FILES=(
    "docs/dev/repo-facts.json"
    "docs/dev/doclets.yaml"
    ".claude/skills/practice-hub-docs-search/doc-index.json"
    ".claude/skills/practice-hub-docs-search/code-index.json"
)

for file in "${GENERATED_FILES[@]}"; do
    if [ -f "$file" ]; then
        git add "$file" 2>/dev/null || true
        echo "   ✅ Staged: $file"
    fi
done

# Stage updated CODE-EXTRACT sections in docs
git add docs/reference/**/*.md 2>/dev/null || true

echo ""
echo "✅ Documentation maintenance complete!"
echo ""
EOF

# Make hook executable
chmod +x "$HOOK_FILE"

echo "✅ Pre-commit hook installed successfully!"
echo ""
echo "The hook will run automatically before each commit and:"
echo "  1. Derive repository facts"
echo "  2. Extract @doc tags from code"
echo "  3. Build unified documentation"
echo "  4. Generate documentation indices"
echo "  5. Validate documentation"
echo "  6. Auto-stage generated files"
echo ""
echo "To skip the hook temporarily:"
echo "  git commit --no-verify"
echo ""
echo "To uninstall the hook:"
echo "  bash scripts/setup-docs-precommit.sh --uninstall"
echo ""
