# Feature Brainstorm Workflow Configuration
name: feature-brainstorm
description: "Athena facilitates brainstorming session to explore feature concept with practice-hub context"
author: "Athena - Requirements Analyst"

config_source: "{project-root}/bmad/phdw/config.yaml"
feature_output_path: "{config_source}:feature_output_path"
user_name: "{config_source}:user_name"
date: system-generated

installed_path: "{project-root}/bmad/phdw/workflows/feature-brainstorm"
template: "{installed_path}/brainstorm-template.md"
instructions: "{installed_path}/instructions.md"

default_output_file: "{feature_output_path}/brainstorm-{{feature_id}}-{{date}}.md"

# Adapts BMAD Core brainstorming with practice-hub context
brainstorming_base: "{project-root}/bmad/core/workflows/brainstorming/workflow.yaml"

standalone: false

